### ISSUE TITLE
PHP Deprecated

### ISSUE THREAD

**Issue by mehrazmorshed** [Codeinwp/tweet-old-post#1013]
Optional parameter $search declared before required parameter $exclude is implicitly treated as a required parameter in 
`/wp-content/plugins/tweet-old-post/includes/admin/models/class-rop-posts-selector-model.php` on line 196

**Comment by girishpanchal30** [comment]
I've reviewed and fixed it here - https://github.com/Codeinwp/tweet-old-post/pull/1015
