### ISSUE TITLE
Whitelist IP message

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/tweet-old-post#108]
Users are getting annoyed by this, I don't think it's working properly, one has said that they are posting just fine but the plugin is giving the whitelist error.

Another said he whitelisted the IP in Wordfence and Cloudways and it didn't make a difference, @selul I believe you said you'd do some type of fall thing for this

**Comment by selul** [comment]
@UVLabs can you share also the site adresses or  tickets url ?

**Comment by UVLabs** [comment]
@selul there have been a few Ill add them when I find them again but here's one: 

https://secure.helpscout.net/conversation/279397970/119457/?folderId=212390

**Comment by UVLabs** [comment]
@selul https://secure.helpscout.net/conversation/281922552/119895/?folderId=844847
