### ISSUE TITLE
add pinterest

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/tweet-old-post#117]
Looks like we can also add pinterest, we can do it through an api endpoint on our site, see url here : https://www.dropbox.com/s/15sitxews5siiuy/Screenshot%202017-03-27%2013.10.19.png?dl=0

cc @selul

**Comment by ineagu** [comment]
I haven't seen any info that they don't like auto-posting apps

**Comment by UVLabs** [comment]
They do have some documentation on it: https://help.pinterest.com/en/articles/limits-and-blocks we just need to recommend users not over do it, I added a note about it to the doc
