### ISSUE TITLE
check facebook auth.

### ISSUE THREAD

**Issue by selul** [Codeinwp/tweet-old-post#118]
@contactashish13 several users reported problems with facebook auth. After they add the app details the popup with pages is empty. 

Can you please investigate what issue could be ? Maybe some facebook api change ? 

Please keep me updated.

**Comment by contactashish13** [comment]
@selul the oAuth response body is now being sent in json. previously it was being sent in url format. I couldnt find any documentary evidence for this change but I've added support for this.

PR: https://github.com/Codeinwp/tweet-old-post/pull/119

**Comment by selul** [comment]
Great. Well done.
