### ISSUE TITLE
Version pre-release

### ISSUE THREAD

**Issue by selul** [Codeinwp/tweet-old-post#147]
@preda-bogdan we need to do a slight change to the migration, as I suspect the activator routine is not really running on the update. 

We can hook this into the plugins_loaded routine, with the highest priority but before any of the new refactor code will run. Basically, the activate method from the new version will be triggered on the plugins_loaded hook.

Let me know after you do this to move forward with the testing.

**Comment by selul** [comment]
@preda-bogdan

- [ ] the migration seems to work ok for Twitter, for facebook not really. After i activate the refactor version, the fb page is moved to the available accounts, but is not set as active -> http://prntscr.com/ihtxc8 

- [ ] Also, we need to a loading indicator for all REST-API requests, i'm fine with adding a basic loader gif wherever you want, we will improve the UI later with someone from the frontend. 
- [ ] the save button is redundant on the accounts tab. 
- [ ] in this state ->  http://prntscr.com/ihtxc8 , if i remove the facebook page from the available accounts, i still can not add any new facebook app ->  http://prntscr.com/ihu08y

**Comment by preda-bogdan** [comment]
@selul I've made some changes.
- Added a new element `ajax-loader` that displays while AJAX requests are in progress
- Removed the Save button
- The issue with Facebook caused the second issue to occur, I've made some changes to the migration and tested on a clean instance it seams to work.

Test and tell me if there are any more issues that should be fixed or improved.

Thank you!

**Comment by selul** [comment]
the facebook/twitter account migration seems to work ok but there are still issues with the migration. 

 - [ ] the general settings migrations is not really working, here is a screenshot before switching -> https://prnt.sc/ik05g8 and after switching https://prnt.sc/ik05g8 
 - [ ] Saved include/exclude taxonomies are not migrated also.
 - [ ] The sharing interval is missing in the general settings for the free version -> http://prntscr.com/ik0bno

**Comment by preda-bogdan** [comment]
@selul at the last bullet point, I don't store that option in general settings, it is part of the schedule witch is available in PRO, should I add an option for LITE?

**Comment by preda-bogdan** [comment]
@selul added a new setting that overrides the global settings defaults for LITE interval also I have removed the readonly state from spinners.

**Comment by ineagu** [comment]
I am not really sure what is happening, however while I am navigating and trying to do things inside the plugin, I get posts added multiple times in the post type select box: https://www.dropbox.com/s/pam61yq8wj9bvxh/Screenshot%202018-03-01%2011.15.52.png?dl=0

**Comment by preda-bogdan** [comment]
@ineagu I think it is fixed now, if you have the time please confirm it is solved.

**Comment by selul** [comment]
@preda-bogdan : 


- [ ] Re: Taxonomies are not migrated.  
    - Before  -> https://prnt.sc/ilbzn6
    - After-> https://prnt.sc/ilc07b
- [ ] When clicking on taxonomies I get -> http://prntscr.com/ilc1jx, as there is no taxonomy to fetch. Also if try to search one, nothing is found.  
- [ ] I try to change the default sharing interval, it gets reverted to 8 whatever I do https://drive.google.com/file/d/1IOpA4i6YOYYXdo175mwheNIaZ-qq1BlE/view Same thing for: 
    - post age min
    - post age max
    - number of posts

- [ ]  There is no start sharing button, similar to the previous version, or I'm hidden somewhere I cannot find it.  I can not figure out how can I start the sharing. 
- [ ] I get this in logs `The shortner service wp_short_url can NOT be built or was not found`, this shortner is inherited from the previous version and is using the core -> `wp_get_shortlink` 
- [ ] i added some accounts on the old PRO and lite, after deactivated the old lite and tried to activate the new LITe i get this -> http://prntscr.com/ilexz4 ( i did have a LinkedIn account if helps ) 
- [ ] i had authenticated most of the services ( https://prnt.sc/ilex5h ), after i deactivate the LITE version and activated the new LITE, no account was migrated ( it was the same environment where i got this error  http://prntscr.com/ilexz4 ) 
- [ ] On twitter auth it's a strange behavior, when i try to sign in, a new windows popups up, if i try to switch the account, it opens a new tab in the old window and until i will not close the previous one, the accounts is not gettings saved. -> https://drive.google.com/file/d/1oW3AkUFRLxrGUlQ03zFJzs1_f_DMwVQK/view 
      We should use the same behavior as in the old version, it was working pretty smooth. 
- [ ] I have the both refactored version active ( lite and pro ), LinkedIn and twitter are still disabled -> http://prntscr.com/ilf6cs 
- [ ] I want to auth with facebook, i get the popup for application details, if i try to to close it, the application freezes -> https://drive.google.com/file/d/15X71OwmrLoZA74HBbF8QNJjPEjxhbowb/view 
- [ ]  I would like to show a countdown, time until next post, which will be always visible, doesnt matter on which tab we are and. The countdown will show the time til the plugin will post on any network/account. Basically the time to the soonest share.

**Comment by selul** [comment]
@preda-bogdan I've also fixed the Travis build, we should make sure that is passing after all of those are fixed.
