### ISSUE TITLE
Setup wizard for ROP

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/tweet-old-post#176]
When you install WooCommerce, there's a Setup Wizard which helps you in configuring WooCommerce for the site, can we do something similar for ROP?

- First, ask users to Connect to social sites
- Then ask them to configure the schedule
- And then filter what they want to include/exclude

Given the type of plugin this is, it can be helpful for new users, as well for promoting Pro version.

What do you think? @selul @ineagu

**Comment by ineagu** [comment]
@UVLabs would be nice to come up with some insights about making sure the pointers works, like a way to tell if they help or not :)

**Comment by UVLabs** [comment]
@ineagu do you have anything in particular in mind? We can add some UTM tags to the links in the pointers to see how much interaction is happening to the Pro feature docs, not sure if you mean something else

**Comment by UVLabs** [comment]
@ineagu ok no problem
