### ISSUE TITLE
Some Minor issues found

### ISSUE THREAD

**Issue by rohittm** [Codeinwp/tweet-old-post#177]
@rodica-andronache @selul Here are few minor issues I found while updating docs for ROP:

1. [ ] Whenever in any number field, I try to remove and add my own number, NaN is shown instead of empty input field. 
![nan](https://user-images.githubusercontent.com/3204558/39835924-623b4b4e-53ef-11e8-971c-ac8c1a903f0b.gif)

2. [ ] While selecting Taxonomy, if the category is selected, then deselected, there is no way to select back those categories, unless the page is refreshed.
![taxonomy](https://user-images.githubusercontent.com/3204558/39835988-93094474-53ef-11e8-89bb-9712c4035bac.gif)

3. [x] When adding a new LinkedIn account, there is a grammar error:
![screen shot 2018-05-10 at 01 16 00](https://user-images.githubusercontent.com/3204558/39836064-d279b756-53ef-11e8-9538-1ee5810c111d.png)

**Comment by selul** [comment]
@rohittm thanks for checking, i was not able to replicate 1 and 2 but 3 was a good catch, i have fixed it.
