### ISSUE TITLE
fixed linkedin instructions

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/tweet-old-post#18]
fixed linkedin intructions adding : OAuth 2.0 Redirect URLs:

**Comment by ineagu** [comment]
@mileamadalin can you investigate if the fb/linkedin instructions are up to date ?

**Comment by mileamadalin** [comment]
@rodica-andronache aici s-a creat deja video-ul pentru facebook si twitter, urmeaza si celelalte in curand.
