### ISSUE TITLE
Hashtag appears before link

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/tweet-old-post#191]
![image](https://user-images.githubusercontent.com/10324144/42423422-d6beb134-82c7-11e8-89b7-8068aa756701.png)

Ideally it should be at the very end

**Comment by UVLabs** [comment]
NTS: test on all networks

**Comment by selul** [comment]
@UVLabs i wont change that right now, there are people who are familiar with this format and i have not seen to many requests on this change. 
i'm afraid this might bring more support requests from users who want back the old format.

Until we won't add in the plugin a way of building the content for sharing based on placeholders, I think we can keep it like this. 
By building content based on placeholders I mean something like this: 

`Some hardcoded test {hashtags} by {sharing_link}`

**Comment by UVLabs** [comment]
It seems like in the past we had hashtags last: https://github.com/Codeinwp/tweet-old-post/blob/3d173498a222d027f2f69eae937e05ead6468a16/inc/core.php#L901

The user mentioned that we only changed it in the update

**Comment by selul** [comment]
@UVLabs i get your point, it's up to you the decision.

**Comment by UVLabs** [comment]
working on this via here: https://github.com/Codeinwp/tweet-old-post/pull/195
