### ISSUE TITLE
Unable to add twitter account

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/tweet-old-post#193]
twitter credentials being fetched incorrectly

```
		$request_token = $this->request_api_token();
		if ( empty( $request_token ) ) {
			return $this->get_legacy_url();
		}
		$this->set_api( $request_token['oauth_token'], $request_token['oauth_token_secret'], $data['consumer_key'], $data['consumer_secret'] );
		$api = $this->get_api();
```

**Comment by contactashish13** [comment]
@selul PR: https://github.com/Codeinwp/tweet-old-post/pull/194

CC @rodica-andronache

**Comment by selul** [comment]
@contactashish13 i don't think we need this, credentials are defined here -> https://github.com/contactashish13/tweet-old-post/commit/e3140eb2c5c1f9408d8cf7f2b767829d1ace3a42#diff-fbfdf2cba2fad46ffd4932c206d08493R325

**Comment by contactashish13** [comment]
@selul I'm not sure what you mean. I was unable to add a twitter account until I made this change.

**Comment by selul** [comment]
@contactashish13 yes, it seems it was wrong set, but for me was working and I haven't seen anyone complain.

The fun fact is that is working with both versions for me.

@UVLabs can you have a look also? Is working fine for you too.

**Comment by UVLabs** [comment]
I haven't seen anything from users as well and it's been working fine for me, I tested the change as well and it still worked though it looks like Ash's configuration is how it should have been

**Comment by selul** [comment]
@UVLabs yep, you're right. i think we can merge it @UVLabs
