### ISSUE TITLE
Make instant sharing message filterable

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/tweet-old-post#213]
https://wordpress.org/support/topic/instant-social-sharing-is-available-on-the-extended-version-for-revive-old-posts/

**Comment by selul** [comment]
@UVLabs i think we can use the same way we dismiss the custom share message metabox, to dismiss that instant sharing upsell and features. The only difference is that by default this should be one but use can toggle this off.

**Comment by UVLabs** [comment]
Do you mean an option in the screen options or on the plugin dashboard?

**Comment by selul** [comment]
something like this -> http://prntscr.com/kt0dco but this time the option will be available to free and pro and by default will be enabled. 

if the option is disabled the upsell message or instant sharing feature will be disabled in the editor screen, otherwise we will show them

**Comment by selul** [comment]
@UVLabs i've added the fix in the pro version which was not compatible with version 8.1 of the free one because you were checking `get_instant_sharing` method of settings model, which was not available in the pre 8.1.1
