### ISSUE TITLE
Switch to bitly OAuth

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/tweet-old-post#244]
Before they fully deprecate API keys:

![image](https://user-images.githubusercontent.com/10324144/47958362-986f6a00-dfa0-11e8-8b04-d43ee9c9ef70.png)

**Comment by contactashish13** [comment]
@UVLabs which keys are you referring to?

**Comment by UVLabs** [comment]
@contactashish13 Bitly

**Comment by UVLabs** [comment]
hey @contactashish13 can you complete this by next week or should I push it to next release?

**Comment by contactashish13** [comment]
@UVLabs hopefully I should be able to :)

**Comment by UVLabs** [comment]
thank you

**Comment by contactashish13** [comment]
@UVLabs PR: https://github.com/Codeinwp/tweet-old-post/pull/266

the generic access token expected by this change can be generated from within the bit.ly account:

![image](https://user-images.githubusercontent.com/12953439/49422221-003fed00-f7b9-11e8-8af7-b57a4d993fa3.png)

PS - can you please implement the suggestions I had made earlier about not keeping credentials in the test cases?
