### ISSUE TITLE
Shares with Image appear with blank space [WP 5.0]

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/tweet-old-post#250]
Posts with image blocks get stripped of the image block(which is correct) but space stays in content 

![image](https://user-images.githubusercontent.com/10324144/48809487-3716fd00-ecfb-11e8-8a64-1931e0f3c64a.png)

![image](https://user-images.githubusercontent.com/10324144/48809512-48f8a000-ecfb-11e8-8a4c-5ac6847da5d0.png)

@HardeepAsrani I'm thinking of simply replacing /n and /r to get around this, any other idea?

**Comment by selul** [comment]
@UVLabs you need to make sure you wont remove all line breaks, and just the duplicate ones, i.e more than 2 one after another. 

You can have a look here on how to do it

**Comment by UVLabs** [comment]
@selul here where?

**Comment by selul** [comment]
sorry, i missed to paste the link -> https://stackoverflow.com/questions/9058093/how-to-remove-duplicate-break-lines-with-php
