### ISSUE TITLE
Publish Now Gutenberg integration

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/tweet-old-post#255]
Logic is here: https://github.com/Codeinwp/tweet-old-post/pull/313/files

**Comment by UVLabs** [comment]
@HardeepAsrani  you think we can have this for v8.1.5 next week? If not i can push it to v8.1.6

**Comment by KumarAbhirup** [comment]
Hey, when I try to connect FB app to the plugin on localhost, things don't work because this plugin needs `https`... any solution? @HardeepAsrani suggested me to use [https://jurassic.ninja/](https://jurassic.ninja/), but it seems to not work for me. Any guidance on how I help solve this issue?

**Comment by UVLabs** [comment]
@KumarAbhirup have you checked out this doc? https://docs.revive.social/article/349-how-to-create-a-facebook-application-for-revive-old-post

Also do you have access to that URL? When you make the facebook app keep it in development mode as you won't be able to actually share anything if it's in live mode. Also let me know if there's any particular error in the plugin log if you're having trouble connecting/sharing.

**Comment by KumarAbhirup** [comment]
Tried everything in the docs, yet seeing this...
![Screenshot 2019-04-21 at 8 35 58 PM](https://user-images.githubusercontent.com/25429790/56471875-2bc82900-6475-11e9-92d9-dca5436f7255.jpg)

To get the Publish now button access, I need to add account as per details given to me by @HardeepAsrani....
```
Add a profile
And then make a new post in Classic Editor.
And you’ll see an option to “Publish Now” on the Public panel of the editor.
We’ve to do the same for Gutenberg.
Let me know once you’ve seen how it works in Classic Editor.
If you need any help then let me know.
You need to connect a social media profile to see it in action.
```

**Comment by UVLabs** [comment]
@KumarAbhirup send me a screenshot of the URL you have in the Facebook app's OAuth Login area. Maybe send a screencast/screenshots of your steps

**Comment by KumarAbhirup** [comment]
As given in blog post, when I enter `Valid OAuth Redirect URIs` as `http://wordpress.test/wp-admin/admin.php?page=TweetOldPost`, it gives this error 👇
![Screenshot 2019-04-22 at 6 21 37 PM](https://user-images.githubusercontent.com/25429790/56501266-bbc8aa00-652b-11e9-8552-6004f3b5392a.jpg)

I'll send a screenrecord ASAP. 🙂
We may hangout on Skype or Teamviewer screenshare if necessary.

**Comment by UVLabs** [comment]
@KumarAbhirup The error is letting you know that Facebook no longer supports authorizing applications via HTTP as a redirect URL, only HTTPS, so you need to use a site with HTTPS, you can use the site hardeep told you about and the error would go away

**Comment by KumarAbhirup** [comment]
Okay, :-) I was never used to work with `ssh` until now. Will have a nice learning experience 👌

**Comment by UVLabs** [comment]
@KumarAbhirup no need for ssh here, we can continue the conversation on slack to help you get your account connected so you can test

**Comment by KumarAbhirup** [comment]
Yup. No need of ssh for connecting, but need it for development, i m right?

**Comment by KumarAbhirup** [comment]
Will get this done soon after I complete my school mock tests :-)

**Comment by UVLabs** [comment]
Awesome

**Comment by HardeepAsrani** [comment]
@UVLabs You can check it here: https://github.com/Codeinwp/tweet-old-post/pull/364 - posts are being added to meta but currently not being sent so you need to fix that.
