### ISSUE TITLE
Custom messages Gutenberg integration

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/tweet-old-post#256]
Logic for custom messages box: https://github.com/Codeinwp/tweet-old-post/blob/master/includes/admin/views/custom_fields_view.php

Method for adding custom messages metabox in classic editor: https://github.com/Codeinwp/tweet-old-post-pro/blob/master/includes/admin/class-rop-pro-admin.php#L130

Method which saves the post's custom messages to the DB: https://github.com/Codeinwp/tweet-old-post-pro/blob/master/includes/admin/class-rop-pro-admin.php#L176

We need to find a way to add the custom messages boxes in a way so they can get POST(ed) by the custom_repeatable_meta_box_save() method on Gut post save. The custom messages boxes need to be **repeatable**

All the rest of the work will be taken care of by the current setup, we just need to find a way to let user be able to create custom messages in a repeatable way(because they act as variations for a post)

**Comment by UVLabs** [comment]
This is a metabox so we might not need to do anything/much here since Gut supports it https://prnt.sc/lp4mcz

**Comment by HardeepAsrani** [comment]
Metaboxes aren't the best, so I'll keep it in the loop and get to it when I'm done with Otter.
