### ISSUE TITLE
Send Log via email

### ISSUE THREAD

**Issue by mariusghitulescu** [Codeinwp/tweet-old-post#27]
Optiunea de a transmite Log-ul pe unul sau mai multe email-uri, preferabil la buton sau schedule la un interval customizabil. 
E buna pt clienti sa afle daca li s-a oprit pluginul si am putea cere si noi sa ne trimita direct un mail cu log-ul cand facem debugging.

**Comment by ineagu** [comment]
E buna ideea, putem pune o setare, gen notify when posts aren't sharing ( max once per week ) .
