### ISSUE TITLE
ugly area on start plugin sidebar

### ISSUE THREAD

**Issue by selul** [Codeinwp/tweet-old-post#271]
@UVLabs i don't know if this was the intended style or is something wrong with the plugin on the site where I have seen this but this area http://prntscr.com/lqzvnv is not looking that good and will more confuse the users in the current format. 

if the intent was to copy the Revive network checklist you can follow the design also as that one was looking much better. 
Moreover using this checklist in combination with those pointers will create more confusion rather than help them, i would stick just to one of them or maybe show them at once, like if pointer tutorial is done, you can show that checklist in the sidebar.

Besides the ugly design that the checklist is using, it should be in his own card, similar with the upsell image. Furthermore, we should keep each step one per line and give more details about those like: 
Two more steps to start using the plugin. 

In adition, we can focus when they click one of the checklist items on the proper action. Like when they click to connect your account, open the network selector area and so on. 

As this is not an easy task and requires a bit of research and work i would postpone the implementation of the checklist and remove it completely from the plugin for now. 

To be on the safe side, on the things/features with visual impact you can propose your solution and ask for feedback from me/andrei/ionut before merging them.

**Comment by UVLabs** [comment]
ok I'll remove it in next version
