### ISSUE TITLE
Redo LinkedIn Documentation

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/tweet-old-post#285]
@purplecodes you wanna take care of this? We currently have a video which isn't really helpful because there's not any text to help with it. I'd say ditch the video entirely and make the doc like our other documents

https://docs.revive.social/article/406-how-to-create-a-linkedin-app-for-revive-old-post

**Comment by purplecodes** [comment]
@UVLabs added this on my list.
Will just do screenshots and texts instead of the video.

**Comment by purplecodes** [comment]
I need to have access to the docs of revive social.

**Comment by UVLabs** [comment]
@mileamadalin can you please give AC access?

**Comment by mileamadalin** [comment]
@UVLabs @purplecodes if you have access at the Revive Social MailBox, you should have access at the docs as well. Can you please confirm me if you are able to see the Revive Social mailbox on HS?

**Comment by purplecodes** [comment]
@mileamadalin thanks. I can see it now. I need to go to HS first to see the edit button.
If I go directly to docs.revive.social, I do not see the option to edit. But this is good for now.
