### ISSUE TITLE
Update review message

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/tweet-old-post#294]
![image](https://user-images.githubusercontent.com/10324144/50123250-65262900-0236-11e9-86fb-df211b196ef6.png)

**Comment by UVLabs** [comment]
@preda-bogdan @selul do you guys remember where you added those strings? I've been doing a project wide search and haven't been able to find where the code is.

I can't remember exactly but I think I took the screenshot from an older install, I think the new message has Marius' name...I've checked: https://github.com/Codeinwp/tweet-old-post/blob/master/includes/class-rop-i18n.php

But can't seem to spot this, if you can't remember then let me know I'll wait to see when it happens on another dashboard to check the source

**Comment by selul** [comment]
This is from the themeisle-sdk repo, what you would like to change there? The message can be filtered.

**Comment by UVLabs** [comment]
@selul I think the copy can be improved, I think the (boost my motivation) can be removed and button text can be changed, to me, it just seems a little too playful, which is not bad but I don't think we have that kind of demeanor with ROP, maybe in Optimole or OrbitFox this type of copy would work better.

**Comment by selul** [comment]
@UVLabs what kind of text have you thought about?

**Comment by UVLabs** [comment]
@selul I'll think of a few and we'll choose one

**Comment by UVLabs** [comment]
@selul 

Review Message Options:

- [ ] Hey! It looks like you've been using Revive Old Posts for a while now. Would you like to help by leaving us a kind review? It would really help :)

- [ ] Hey! It's the Revive Social team, it looks like you've been using our Revive Old Posts plugin for a while, we hope it's been a real help! Would you mind leaving a us a kind review?

- [ ] Hi there, Revive Social team here, we noticed you've been using our plugin for a while now, has it been a great help? If so, why not leave us a kind review? It would help a ton, thanks!

- [ ] Hey, has Revive Old Posts helped boost your website traffic? If so, would you mind leaving us a kind review? It would really help, thank you!

Buttons options (yes, no respectively):

- [ ] Sure!

- [ ] No thanks
----

- [ ] Ok

- [ ] No thanks
----

- [ ] Yes

- [ ] No thanks
----

- [ ] Help ROP

- [ ] No thanks

**Comment by selul** [comment]
@UVLabs I like the 3rd one. @FitzChris do you have any feedback too?

**Comment by selul** [comment]
I've edited the message here https://github.com/Codeinwp/tweet-old-post/pull/296 + changed the uninstall feedback icon which was using the themeisle one instead of revive old post and few more tweaks to the labels which were referring to themeisle instead of ReviveSocial.
This is how the message is currently looking: http://prntscr.com/m0j2z7 

The SDK is configured to show admin notices one at a time, after 100h since plugin install, for 1 week since the user will first see the notification, so you might not see it right away.
