### ISSUE TITLE
PHP Warning:  Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by Sweepr** [Codeinwp/tweet-old-post#305]
UTC] PHP Warning:  Invalid argument supplied for foreach() in /wp-content/plugins/tweet-old-post/includes/admin/models/class-rop-queue-model.php on line 118

PHP version: 7.2.13

Revive Old Posts Version 8.1.7

**Comment by UVLabs** [comment]
Hi, can you create a ticket on our support platform so we can check out your environment? You can do so here:

https://revive.social/contact

Enter "free" where it asks for license

**Comment by Sweepr** [comment]
Just to inform that the issue has been resolved,

Thank you!
