### ISSUE TITLE
PHP error for pointers

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/tweet-old-post#306]
Fatal error: Can’t use function return value in write context in /home4/carols/public_html/wp-content/plugins/tweet-old-post/includes/admin/class-rop-pointers.php on line 55

Plugin should be deactivating automatically on PHP versions lower than 5.6...investigate why this error is occurring

**Comment by preda-bogdan** [comment]
[HERE](https://github.com/Codeinwp/tweet-old-post/blob/0e6c4c7aa74ef66e30ba17939a617191a02393f5/includes/admin/class-rop-pointers.php#L55)
 You should not apply `empty` on a function return, assign the `get_option` to a variable and then check for the value, that should fix the issue.

**Comment by UVLabs** [comment]
@preda-bogdan Yes I'm aware of this but we actually are trying to bring users up in PHP versions and automatically deactivate ROP Lite on PHP < 5.6 https://github.com/Codeinwp/tweet-old-post/blob/master/tweet-old-post.php#L95 

It seems to be because the pointer code runs before the deactivation one, I'll assign the value to a variable first like you said
