### ISSUE TITLE
Facebook app not posting (app already approved)

### ISSUE THREAD

**Issue by purplecodes** [Codeinwp/tweet-old-post#307]
Few users have reported that the Facebook app not posting.
Error: "Unable to share post for Facebook. Error: (#200) Requires either publish_to_groups permission and app being installed in the group, or manage_pages and publish_pages as an admin with sufficient administrative permission"

Tickets: 
https://secure.helpscout.net/conversation/750604106/177483?folderId=844842
https://secure.helpscout.net/conversation/763875327/178885?folderId=844842
https://secure.helpscout.net/conversation/763862121/178883?folderId=844842

**Comment by UVLabs** [comment]
Wasn't able to reproduce this, With the new facebook login workflow we can simply let users know they can log in using our app.
