### ISSUE TITLE
Add Publish Now feature to Lite plugin(?)

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/tweet-old-post#312]
I'm aware this is a pro feature but I might help users get their apps approved with Facebook. One major thing Facebook wants to see in the screencast is that a post being made in the dashboard and appearing on Facebook.

There are two ways we can help users with this:

1 - Create a watered down plugin/version of ROP which has the Share immediately option which the user can use to create the screencast for ROP

2- Add the publish now feature to the Lite plugin.

Here's an example of what a reviewer message typically is:

> I’ve taken a look at the errors shown in your screenshot. Please make sure to set your app in development mode in the top right hand corner of your developer dashboard. Once you do so, you can use the Graph API Explorer to create a temporary access token to the manage_pages and publish_pages permissions to show the proper use case of the permissions in your screencast. You can find the Graph API Explorer here: https://developers.facebook.com/tools/explorer/.
> To reiterate, in your screencast for publish_pages/manage_pages, please show the creation of the post in a custom composer (ie. typing it out), and then show that published post on the Facebook page that it is posted on (all in real-time). The review team will need to see the post on the Facebook page immediately after it has been published

@contactashish13 @selul

**Comment by selul** [comment]
@UVLabs thinking about this I feel like you are right. 
Let's avoid extra complexity and move the publish now into the free version, eventually the value that the pro plugin brings in, lays in more accounts where they can share, which affects this feature too. 

We should make sure to: 
- [ ] Remove the publish now feature among the pro features in the readme and sales page and add it among the free features.
- [ ] The 1 Facebook and 1 twitter account limit would be inherited to this share now feature along with a non-intrusive link to the pro version if they want more ( in the publish now meta box )
- [ ] on the new free version install, show a notification in the Rop dashboard letting them know about the feature. 
- [ ] We can bump this to a minor version, i.e to 8.2.0 version

**Comment by UVLabs** [comment]
@selul in the free version of the plugin it's already not possible to add more than one account for twitter and facebook, did you have something else in mind or forgot?

**Comment by selul** [comment]
@UVLabs yes, i was saying just to make sure we will have this in the publish feature too.
