### ISSUE TITLE
Parse Error in ROP v 8.2

### ISSUE THREAD

**Issue by FitzChris** [Codeinwp/tweet-old-post#316]
Parse error: syntax error, unexpected '[' in /var/sites/h/helenochyra.com/public_html/wp-content/plugins/tweet-old-post/includes/class-rop.php on line 180

The tweet:
https://twitter.com/helenochyra/status/1095259033920069632

**Comment by preda-bogdan** [comment]
@FitzChris it's because he uses a version of PHP less than 5.4, it is specified that it requires at least PHP 5.6, I think it's a mute issue.

**Comment by FitzChris** [comment]
@preda-bogdan Wow. Didn't realise that was still possible; thanks mate.
