### ISSUE TITLE
don't use photon for twitter images

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/tweet-old-post#338]
Libraries such as the one used for twitter in the plugin requires that the image be present on the server, so using Jetpack's photon might result in an error because the image cannot be downloaded and uploaded to Twitter by the library.

https://github.com/abraham/twitteroauth/issues/768

https://ethitter.com/2013/07/disable-jetpacks-photon-module-in-specific-situations/

**Comment by mariusvetrici** [comment]
Bypassed Jetpack Photon/Site Accelerator hooks so the image URL is pointing to the locally-stored image. Images should now be shared to Twitter even with Photon/Site Accelerator enabled.
