### ISSUE TITLE
Confirm and Include guzzle dependency in plugin

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/tweet-old-post#357]
Doesn't seem like guzzle was included in the actual plugin, though the functions were working for me, might have been getting called from a different source.

https://github.com/Codeinwp/tweet-old-post/pull/356

Test with linkedin api v2 changes made previously

**Comment by selul** [comment]
@UVLabs I'm not sure why we need this?

**Comment by UVLabs** [comment]
@selul while upgrading to linkedin api v2 i was using guzzle to make the request to upload the image that would be attached to a post; thinking it worked because guzzle might have already been included in the plugin (my mistake) https://github.com/Codeinwp/tweet-old-post/blob/master/includes/admin/services/class-rop-linkedin-service.php#L570

I will revisit this and try to accomplish it without guzzle as we might not need it to begin with

**Comment by selul** [comment]
@UVLabs makes, sense. we can keep it in this case.
