### ISSUE TITLE
fb popup issue

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/tweet-old-post#39]
@selu91 here is how the popup look for me in chrome : https://www.evernote.com/l/AY-WVcOY-3FP6KRF7QY-smcjlCGrPvKFVvI, I also think the steps listed here are outdated .

**Comment by selu91** [comment]
cant replicate

**Comment by ineagu** [comment]
ok might be a plugin conflict, steps listed were updated ?

**Comment by selu91** [comment]
yes, i've added the facebook video tutorial also.

**Comment by ineagu** [comment]
cool

On Fri, Sep 18, 2015 at 4:54 PM, Marius Cristea <notifications@github.com>
wrote:

> yes, i've added the facebook video tutorial also.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/tweet-old-post/issues/39#issuecomment-141475082>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by ineagu** [comment]
@selu91 in the same fashion, in the fb popup you written fallow instead of follow, it should be fixed ;)

**Comment by ineagu** [comment]
still fallow ?

**Comment by ineagu** [comment]
we need to fix this

**Comment by ineagu** [comment]
@contactashish13 can you take a look at this as well in case isn't done ?

**Comment by ineagu** [comment]
I am talking about the type : fallow instead of follow
