### ISSUE TITLE
Open up new Facebook workflow to old accounts

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/tweet-old-post#399]
@selul I've been having to tell users with old installs of ROP how to get the new workflow. It's been a month and some weeks now with no issues regarding the new workflow, I was thinking of opening it up so users don't have to re-setup the plugin in order to see the sign into facebook button option.

**Comment by selul** [comment]
Not sure I understand the course of action, what are you trying to do or what's the plan ?

**Comment by UVLabs** [comment]
@selul currently the new easier workflow is not being shown to users who had rop prior to v8.3.0, remember you said we should only make it available to new users as a way to test this out?

https://github.com/Codeinwp/tweet-old-post/blob/master/vue/src/vue-elements/sign-in-btn.vue#L23

https://github.com/Codeinwp/tweet-old-post/blob/master/includes/admin/services/class-rop-facebook-service.php#L731

I'm saying it's been a month and some weeks since we've been test running this so I think it's safe to now remove this restriction for older users that might have given up on Facebook and not aware that it is now easier (they wouldn't have seen the option at all).

I've had to walk some olders through to how to get the new option shown, I'm saying we should open this up now in case an older user might be trying to give Facebook another shot so they can see the new easier method

**Comment by selul** [comment]
yes, I agree, we can move to the next phase.
