### ISSUE TITLE
Remove + Add account button

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/tweet-old-post#405]
@selul I think we can save the user a click by removing the gree + account button and just having the accounts present and ready to be connected:

![download](https://user-images.githubusercontent.com/10324144/61483750-79b4d600-a96b-11e9-9eaf-0f9936484897.png)

---

**New look:**

![download (1)](https://user-images.githubusercontent.com/10324144/61483697-6570d900-a96b-11e9-8ae2-29290bc37b48.png)

---

![download (3)](https://user-images.githubusercontent.com/10324144/61483713-6b66ba00-a96b-11e9-8097-94c377a83919.png)

**Comment by selul** [comment]
Yes, I agree.

**Comment by ineagu** [comment]
Probably we can still keep the add account text on that line, or do something like we had before : https://www.dropbox.com/s/rkakrfkrqpa7jxw/Screenshot%202019-07-19%2009.25.14.png?dl=0, which keep the social network icon, but then replace the name with add account. if we just drop that and leave the icons, would be quite hard to figure out that I can click those to add an account

**Comment by UVLabs** [comment]
Ok I'll come up with 1 or 2 possible implementations we can use and we'll decide on one

**Comment by UVLabs** [comment]
@ineagu @selul 

**Option 1:**

![image](https://user-images.githubusercontent.com/10324144/61710947-df64e180-ad20-11e9-9aa7-4b12f2081e14.png)

**Option 2**

![image](https://user-images.githubusercontent.com/10324144/61710972-ef7cc100-ad20-11e9-89f3-0ea04fca3b40.png)

I'm leaning towards Option 1, what do you think?

**Comment by ineagu** [comment]
What if we separate the buttons on 1?

Also can we show the 1-account limit notice only when user reached the limit? In the screenshoted state we want user to focus on adding an account not overloading the screen with infos

**Comment by UVLabs** [comment]
@ineagu are you talking about separation like this?

![image](https://user-images.githubusercontent.com/10324144/61712527-8a2acf00-ad24-11e9-8ff7-e0f4968c3f5b.png)

Yes we can set it up so that message only shows when the limit is reached

**Comment by ineagu** [comment]
yep exactly, the concern for me was that is not super clear that those are click-able, it looked a bit more of a banner image.
