### ISSUE TITLE
add google my business posting

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/tweet-old-post#415]
cc @UVLabs

**Comment by UVLabs** [comment]
@ineagu I think we'll have to look into this a bit to see how much interest there actually is, it really is one of those services that I've heard very little about when it comes to being dynamic(like a facebook wall, twitter feed etc), I _think_ people usually just claim their business on the map and forget about the whole thing.

We'll have to see how other services/plugins are actually making use of the feature

**Comment by ineagu** [comment]
yep sure, I've added it as a note, google is pushing this it seems

**Comment by UVLabs** [comment]
Ok we'll see how it's doing
