### ISSUE TITLE
Better matching of error messages

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/tweet-old-post#420]
The solution link being given is the wrong one for the error given: 

![image](https://user-images.githubusercontent.com/10324144/62467358-902ba180-b761-11e9-9061-db9557703d52.png)

A better checking function than strpos() might need to be used such as preg_match() https://github.com/Codeinwp/tweet-old-post/blob/master/includes/admin/abstract/class-rop-services-abstract.php#L481

**Comment by mariusvetrici** [comment]
Issue had 2 parts:
- Trying to run strpos() with the $response variable as the haystack, which was an object, not a string
- Using the same variable name ($link) in the error message as in the foreach loop.

Created [PR 424](https://github.com/Codeinwp/tweet-old-post/pull/424) to fix this.

Alex N.
