### ISSUE TITLE
Show delete icon once account is deactivated

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/tweet-old-post#429]
Right now you have to deactivate the account and then hover over it to see the delete icon.

It would be better UX to simply show the delete icon when the account is deactivated:

![image](https://user-images.githubusercontent.com/10324144/62971625-4cc7d780-bde0-11e9-9278-9b9085fb0248.png)

**Comment by mariusvetrici** [comment]
Changes were implemented successfully! https://d.pr/v/yT1mY1 

The delete icon is not displayed without requiring users to mouse-over the account. 
Bogdan
