### ISSUE TITLE
Test plugin with latest composer dependencies, set strict constraints

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/tweet-old-post#438]
Test latest versions of dependencies with the plugin such as the API wrappers we use:

- Facebook
- Twitter
- LinkedIn
- Tumblr
- Pinterest

As well as monolog, also the themeisle SDK 

Once confirmed working, set strict constraints on those dependencies and commit composer config. 
Set constraint to last confirmed working version of the dependency to avoid unforeseen issues with travis deployment 

Set task to check these dependencies for updates every few months.

**Comment by selul** [comment]
you can setup renovate to keep the dependencies up to date.

**Comment by UVLabs** [comment]
@selul for this it was more so that we can always make sure travis is installing a confirmed working version of a dependency instead of always installing the latest or a version that might not be tested fully with the plugin.

So I think it's best we make the dependencies strict and check for updates manually and test against the plugin before release
