### ISSUE TITLE
Switching from queue to other tabs refreshes queue

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/tweet-old-post#446]
Each time we switch from the queue tab to another tab it refreshes the posts to be shared. 

https://www.loom.com/share/198c7a05a0b34516b80c78704c16729c

Expected behavior:

Switching to the queue tab should always show the same posts in the order they are set to be posted

**Comment by mihaiiro** [comment]
The forced Queue clear action happened because there was a flawed logic check.
```PHP
	private function get_queue( $data ) {
		$queue = new Rop_Queue_Model();
		if ( isset( $data['force'] ) ) { // < -- Force is always on the difference is that it can have FALSE or TRUE as  value.
			$queue->clear_queue();
		}
		$this->response->set_code( '200' )
		               ->set_data( $queue->get_ordered_queue() );

		return $this->response->to_array();
	}
```

**Comment by mihaiiro** [comment]
If you have a few posts, the "Sharing Queue" takes the posts and prepares a schedule for them in order to share them in the future. https://screencast.com/t/xCrQ57yS

The issues seem in the logic of Queue creation, spamming same posts over and over in different days and at different hours.

**Comment by UVLabs** [comment]
@mihaiiro Please ensure the change you did here doesn't affect this one: 

Issue: https://github.com/Codeinwp/tweet-old-post/issues/421
Commit which fixed it: https://github.com/Codeinwp/tweet-old-post/pull/422/commits/d43431d69eb1163fd318527bcc2477e9de3c36cc

**Comment by mariusvetrici** [comment]
Looks good! The issue did not regress: https://d.pr/v/V5yw3y
