### ISSUE TITLE
mobile ready 

### ISSUE THREAD

**Issue by selu91** [Codeinwp/tweet-old-post#47]
We need to make the ROP admin interface mobile ready. Ideally i would not like to make any markup changes, just css media queries. This is how it looks now: 

http://prntscr.com/aquymk

We need to hide the sidebar and the upper area and make available only the tabs menu. 

let me know how do suggest the mobile to look like before moving forward to implementation

**Comment by claudiuvertistudio** [comment]
![rop-v1](https://cloud.githubusercontent.com/assets/3263086/14521286/471ad90e-0231-11e6-8996-bed73f2be8b8.jpg)
![rop-v2](https://cloud.githubusercontent.com/assets/3263086/14521287/4730ba8a-0231-11e6-892f-e848cc1a3d56.jpg)

**Comment by selu91** [comment]
@claudiuvertistudio it's ok. You can push the changes to development
