### ISSUE TITLE
Changes in add account buttons

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/tweet-old-post#478]
There are two tasks here:

## 1 - After one account is added, collapse the rest of the accounts, like this:

**Before any account connected:**

![image](https://user-images.githubusercontent.com/10324144/65839366-a164da80-e2da-11e9-93d4-f0c3212b0d56.png)

**After an account has been connected:**

![image](https://user-images.githubusercontent.com/10324144/65839364-9611af00-e2da-11e9-9843-dd607ea8f810.png)

_We already have functions within the plugin to check when an account is connected_

Here's an example of how this collapsed state would appear once clicked(click to view larger):

![Add account collapsed](https://user-images.githubusercontent.com/10324144/65839380-cb1e0180-e2da-11e9-9347-7d4b0bf4effd.png)

Things to note:

- Icons should be aligned for all the networks

## 2 - Inform users about pro license

If the user tries to click or hover over the disabled accounts, show a tooltip letting them know those accounts require the pro plugin.

**Comment by UVLabs** [comment]
@contactashish13 Lets aim to have this at v8.5.5 (October 16th), if you have any questions dont hesitate to reach out, I'll try my best to assist

**Comment by contactashish13** [comment]
@UVLabs I'm not sure I understand the first issue. Currently the accounts appear in a horizontal line and your wireframe shows that you want them to appear in a vertical stack when the add more accounts button is clicked - that doesn't seem to make sense. Shouldnt they be horizontally stacked just like before?

Also from the perspective of UX, whats the point of making the user click twice just to add an account? What's the harm in the existing implementation where the added accounts are shown together with the add buttons?

**Comment by UVLabs** [comment]
@contactashish13 Currently the accounts are all horizontal, in a continued effort to clean up the UI from unnecessary visual items https://github.com/Codeinwp/tweet-old-post/issues/477, after the addition of 2 social network accounts (**Not to be mistaken with two accounts from the same social network**, _sorry I didn't mention this before_) collapse the rest

The reasoning behind this is that once users add their accounts of choice(for free users this is Facebook and Twitter) the rest of the networks would serve little need to them, so we can make the dashboard more visually appealing by collapsing the unused networks

**Comment by contactashish13** [comment]
@UVLabs declutter makes sense. But should the buttons be horizontal or vertically stacked? If the latter, then will you be taking care of stacking them vertically **as default** so that the user does not get confused when a horizontal stacking without any accounts changes to vertical stacking with accounts?

**Comment by UVLabs** [comment]
@contactashish13 Let's keep it horizontal when the "Add more accounts" is clicked, make this button interactive so that when the button is clicked, the accounts are shown, and when it's clicked again, hide the accounts, on refresh the accounts would always be hidden
