### ISSUE TITLE
small changes

### ISSUE THREAD

**Issue by selu91** [Codeinwp/tweet-old-post#52]
@contactashish13 after you choose delete: http://prnt.sc/awkj8b you retain the value for the next delete actions. I would like to reset the delete behaviour if the user stop the plugin and next time when he will start it to choose again the behaviour. 

Also i get this http://prntscr.com/awkryg after i delete the only post from the 25 april. 

Please pull the changes before work.

**Comment by contactashish13** [comment]
Do you want to reset this when user stops the
a) Pro plugin
b) Free plugin

both a) and b) or only a)?

**Comment by selu91** [comment]
let do for both.
