### ISSUE TITLE
Add Custom share messages

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/tweet-old-post#55]
@selu91 I was thinking about a small feature that we can add : 

1) Add a new box like Remote check in the sidebar, saying : Enable Custom Share Messages

2) When this is activated a new textarea metabox is added to all posts ( or cpt selected ) so a user can enter some custom content.

3) When this is ON and there is custom content, this is choosen over post format settings.

For example if I write an expert roundup, I want when ROP re-share that post to have a very specific format like : Check out what experts like @x @y @z are saying about WP - link.com 

Ideally if is not too complex, we can have a repetable text area so a user can add multiple possible templates and ROP picks one randomly .

**Comment by selu91** [comment]
Dont you think it should be enabled in the post editor, where is the textarea also ?

**Comment by ineagu** [comment]
don't get it

On Thu, May 19, 2016 at 3:48 PM, Marius Cristea <notifications@github.com>
wrote:

> Dont you think it should be enabled in the post editor, where is the
> textarea also ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/tweet-old-post/issues/55#issuecomment-220329215>
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by selu91** [comment]
You are saying to have a global setting, in the plugin settings when this would be on and off. 

I'm thinking it should be better to have this in the post page, maybe user would like to use the custom content just on some posts, and not all

**Comment by ineagu** [comment]
yep, the textarea will appear on all posts, however when the global setting
is off, the textarea doesn't appear. The point is that we don't want to
show things on post editor screen if the user doesn't need it ( I know he
can hide it, manually as well, however I think is good to also have a
default OFF global setting )

On Thu, May 19, 2016 at 3:53 PM, Marius Cristea <notifications@github.com>
wrote:

> You are saying to have a global setting, in the plugin settings when this
> would be on and off.
>
> I'm thinking it should be better to have this in the post page, maybe user
> would like to use the custom content just on some posts, and not all
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/tweet-old-post/issues/55#issuecomment-220330682>
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by selu91** [comment]
I understand, let's do it like this then

**Comment by UVLabs** [comment]
@selul @ineagu maybe we could have a global custom message for specified categories also so users can select, had a customer request this.

**Comment by ineagu** [comment]
@selul can we move this to pro version only ?

**Comment by selul** [comment]
added on the 1.9.0 release
