### ISSUE TITLE
Bit.ly API v4

### ISSUE THREAD

**Issue by FitzChris** [Codeinwp/tweet-old-post#579]
@UVLabs  User on Twitter asks:
are you guys planning to add http://bit.ly API v4 support to Revive Old Posts? They keep emailing me about it, thanks!

The Tweet is here:
https://twitter.com/mojosarmy/status/1236301810815520769

**Comment by UVLabs** [comment]
Responded and started DM, this shouldn't affect users using the general access token which we've made the standard in the plugin some versions back: 

https://support.bitly.com/hc/en-us/articles/360004395631-Migrating-from-v3-to-v4-of-the-Bitly-API

https://docs.revive.social/article/976-how-to-connect-bit-ly-to-revive-old-posts
