### ISSUE TITLE
fatal error when used with latest monolog library

### ISSUE THREAD

**Issue by selul** [Codeinwp/tweet-old-post#588]
When there is another plugin that uses the Monolog library, the latest version, it throws an error if ROP is also activated. 

Error details: 
```
PHP Fatal error:  Declaration of Rop_Log_Handler::write(array $record) must be compatible with Monolog\Handler\AbstractProcessingHandler::write(array $record): void in /wp-content/plugins/tweet-old-post/includes/admin/helpers/class-rop-log-handler.php on line 133
Fatal error: Declaration of Rop_Log_Handler::write(array $record) must be compatible with Monolog\Handler\AbstractProcessingHandler::write(array $record): void in /wp-content/plugins/tweet-old-post/includes/admin/helpers/class-rop-log-handler.php on line 133
```
 This is happening because the latest version of Monolog contains a different method signature for the write method, which ROP implements it. 

cc: @UVLabs

**Comment by UVLabs** [comment]
@selul can you tell me which plugin you were using so I can test this out once I implement the patch?

**Comment by selul** [comment]
I have come across by using the latest version from `edd-fastspring `but you will run by this issue if any plugin will use the latest version of Monolog.

**Comment by UVLabs** [comment]
Ok, i'll update the composer file, we set strict dependencies some months ago to prevent unforeseen issues after travis deploys

**Comment by selul** [comment]
Updating the library won't solve the issue. 

I will try to detail here the issue: 
1. If we update the library and there is another plugin using Monolog 1.x and ROP uses 2.x, we will run into the same issue. 
2. If we keep the same version, and there is a plugin with Monolog 2.x, it will be the same issue. 

Basically from my point of view, the solution might be:
1. Ditch Monolog and implement our logger, as the functionality is not that complicated to use a 3rd party library. 
2. Use Monolog and use a tool like https://github.com/humbug/php-scoper to change the namespace of the library to avoid conflicts.
