### ISSUE TITLE
problem with shortners

### ISSUE THREAD

**Issue by selu91** [Codeinwp/tweet-old-post#60]
@contactashish13 we have a problem with the shortners, bit.ly or is.gd.

Because of the manage queue, at each page refresh we trigger the link shortening services for each post, e.g 20/100 calls per page request. 

I would like, if the user has chosen to use bit.ly or is.gd, to use a placeholder in the manage queue list, either [bitly_link] or [is.gd link]. 

When the user will choose to edit, we will show the shortened link, not placeholder,  in the textarea. 

Let me know if you have any questions.

**Comment by ineagu** [comment]
@contactashish13 Looks like the shortner placeholder appear just for twitter and not for FB : https://www.dropbox.com/s/wxftnczein954h6/Screenshot%202016-05-26%2017.25.39.png?dl=0

**Comment by selu91** [comment]
@contactashish13 also please make the default tab active the All networks tab.

**Comment by selu91** [comment]
@contactashish13 the first tab is selected but on the list we still show the twitter ones http://prntscr.com/b9129a 

Please try to test more when commiting, this is a very important product and we should be careful when releasing.

**Comment by selu91** [comment]
@contactashish13 i have thought more about this, we have no issue with shortners by not showing in the manage queue, the fact is that only for twitter the link is part of the message, for the rest of the networks, we have special field in the api which we are using it, so in the Manage queue we show the message component of the finalTweet only, that's why the link is not present. 

Please revert the changes of the tweet generation back

**Comment by selu91** [comment]
fixed here https://github.com/Codeinwp/tweet-old-post/commit/07e8d95b4c5f3b187ea2d65e2e276ce79d962779
