### ISSUE TITLE
Instant sharing custom message filter

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/tweet-old-post#621]
Add filter to instant sharing custom message so users can overwrite message

**Comment by ckeeney** [comment]
Are PR's accepted into this repo?  I'm happy to open one if so. 

I think supporting this is as simple as adding a filter in [`rop_cron_job_publish_now`](https://github.com/Codeinwp/tweet-old-post/blob/752d21ea5991899db17dd017fd802d21281adde2/includes/admin/class-rop-admin.php#L916-L918):

```diff
$post    = $event['post'];
$message = ! empty( $event['custom_instant_share_message'] ) ? $event['custom_instant_share_message'] : '';
+ $message = apply_filters('rop_instant_share_message', $message, $event);
$account_data = $services_model->find_account( $account );
```

**Comment by ckeeney** [comment]
For completeness, here is example code to utilize the new hook.  

The following hook uses the custom message entered into the metabox.  If the metabox custom message is empty, the filter uses the regular post title ignoring any formatting set in the ROP admin panel.

```php
function revive_old_post_instant_share_message( $message, $event ) {
    $postID = $event['post'][0];
    return $message ? $message : get_the_title($postID);
};

add_filter( 'rop_instant_share_message', 'revive_old_post_instant_share_message', 10, 2 );
```

**Comment by UVLabs** [comment]
@ckeeney A more useful use-case for this filter would be prefixing the custom message for posts in certain categories with some text. https://developer.wordpress.org/reference/functions/wp_get_post_categories/

So you get the post id, check if it belongs to a certain category, and if it does; prefix it with some text. 

An example would be a news website with several writers creating stories, if a story is in a category "politics", the admin might want all instant shares to be prefixed with `"Get the scoop! New from Cat Island Politics: " . $message`

Haven't gotten around to creating the doc but this is what I was thinking would be a good example for this filter.

**Comment by ckeeney** [comment]
I didn't give much context with my code example above, but we're using it to distinguish between new and old articles.  I set the additional text of the Post Format to `ICYMI {date} - `, so revival shares all have `ICYMI - ` prefixed to the title, and that ICYMI prefix is overridden for instant shares.

I do need to customize the messages based on category, but for that feature to be useful I think a second filter is necessary to customize the revival shares as well.  My use case is to distinguish opinion articles from news articles in the shares.  The filter added in the most recent version would only let me distinguish op-eds for instant shares; I currently just exclude all opinions to avoid misrepresenting them as news.
