### ISSUE TITLE
Sample post isn't workin

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/tweet-old-post#63]
@contactashish13 @selu91 Here is how sample post is looking https://www.dropbox.com/s/9c4rdb8r7qg56i9/Screenshot%202016-05-26%2017.26.48.png?dl=0 , we need to fix it :)

**Comment by selu91** [comment]
@contactashish13 here are you using the img tag, but the variable already contains it: 

https://github.com/Codeinwp/tweet-old-post/blob/production/inc/core.php#L551

**Comment by selu91** [comment]
@contactashish13 dont forget about this

**Comment by selu91** [comment]
fixed here https://github.com/Codeinwp/tweet-old-post/commit/07e8d95b4c5f3b187ea2d65e2e276ce79d962779
