### ISSUE TITLE
Improve share only once workflow

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/tweet-old-post#681]
When the "share more than once" option is unchecked, the plugin will share all posts and then give a message that its done. It will also send an email to the admin.

The notice log message about no more posts found will keep filling up the log until the user comes to stop and start the sharing again

**Comment by UVLabs** [comment]
related https://github.com/Codeinwp/tweet-old-post/issues/735

**Comment by stefan-cotitosu** [comment]
It was addressed in version 9.1.0. [here](https://github.com/Codeinwp/tweet-old-post/pull/987/commits/4abd9b727fcbc4c443d4231325b3215446664ade).
