### ISSUE TITLE
Specify that magic tags are available only in pro version

### ISSUE THREAD

**Issue by irinelenache** [Codeinwp/tweet-old-post#689]
When using the basic version of ROP, in `Post format > Additional text`  is mentioned that it supports magic tags, but only after going to `Learn more` on revive social page, it's noted that the magic tags are available only on pro.
https://prnt.sc/v27wpn
https://prnt.sc/v27x2b
It's a bit confusing so would be good to have a notice to `Additional text` field that specifies that the Additional text is available in the basic version and adding a magic tag is available in the Pro version.

**Comment by UVLabs** [comment]
@irinelenache Thank you!
