### ISSUE TITLE
Order of items in queue changes after share happens

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/tweet-old-post#698]
@irinelenache Can you help me confirm this?

Connect say...3 test accounts to the plugin. Create say 5 test posts. Click start sharing, **after this first share happens** and shares are sent to the 3 accounts, go to the **Share Queue**. Make note of all the **upcoming share items**.

When the **next share** comes around, check the log to see if the posts shared were the actual posts that had to be shared according to the previously queued items(that you marked down) as well as to the respective account the queue card listed. 

Then, go back to the **Share Queue** area and see if the next batch of scheduled queue items corresponds with what you previously marked down as well. To keep track easily name the posts as "Post 1", "Post 2", "Post 3" etc etc. 

How it should be working, say **after the initial share** happens the queue looks like this:

- Post 2 
- Post 1 
- Post 3 
- Post 6
- Post 5
- Post 4
- Post 7
- Post 8
- Post 9

If you check the logs after the **next set of shares happen**, then the posts that should have gone out are:

Post 1,2,3 (order doesn't matter here)

When you go back to the sharing queue, then the order of the queue should now be:

- Post 6
- Post 5
- Post 4
- Post 7
- Post 8
- Post 9
...
...
...

The accounts it's set to share to will also be the same as what you initially took down. Please reach out on Slack if you need some more explanation

Use the current version of ROP from the wp.org repo to test this

**Comment by irinelenache** [comment]
@UVLabs I tested it and indeed there is a problem and i'll try to explain it:
If the sharing queue (for **3 accounts**, **1 post per account**) is `1 , 2 , 3 , 4 , 5 , 6 , 7`, the first 3 shared are `1 , 2 , 3` and the queue doesn't change to become `4 , 5 , 6 , 7 ,.... ` . Only the first 3 change randomly and the rest of the queue remains the same. So in this case, the queue becomes `5 , 2 , 1, 4 , 5 , 6 , 7` (5, 2, 1 are random numbers and the rest is the same). After any amount of shares, only the numbers for the next share change and rest of the queue remains the same.
Hit me up if i didn't made myself clear enough.

**Comment by UVLabs** [comment]
Thank you @irinelenache
