### ISSUE TITLE
shortners

### ISSUE THREAD

**Issue by selul** [Codeinwp/tweet-old-post#70]
@contactashish13 can we add in the 3 more shortners in the list. I would like to have google's one in the list and you can do some research to add 2 more, whatever you think is ok.

**Comment by contactashish13** [comment]
@selul the front end shows only 3 but the code apparently has support for 8 (is.gd, bit.ly, tr.im, 3.ly, tinyurl, u.nu, 1click.at and t.co). which ones do you want to go with besides goo.gl?

**Comment by contactashish13** [comment]
@selul can you also tell me why the others were discarded and only 3 retained?

**Comment by selul** [comment]
Hey, 

Honestly i dont know, you can try them to see if are working and add them.
Thanks!

**Comment by contactashish13** [comment]
@selul do you want me to include http://www.tiny-url.info/open_api.html? Appears to be an aggregator. or do you prefer to go with individual services?

**Comment by selul** [comment]
We can skip that.
Pe 25 iun. 2016 12:33, "contactashish13" <notifications@github.com> a scris:

**Comment by selul** [comment]
The shortners are not working ok, i have selected http://prntscr.com/brk6j5 and i get this when i select view sample post ? http://prntscr.com/brk6pj 


Any clue ?

**Comment by contactashish13** [comment]
@selul the shorteners dont work on localhost URLs. They fail - you can see this by going to is.gd and trying to shorten a localhost URL. That is why I have added a fall back for it to display the original URL.

**Comment by selul** [comment]
@contactashish13 ah, got it. But in the view sample, i think the url should not been encoded ?

**Comment by contactashish13** [comment]
@selul the url is being encoded before being sent to the shortener. and if the shortener fails, the same encoded url is being show. do you want the fall back option to be without encoding?

**Comment by selul** [comment]
yes, please show on the view sample popup without encoding if fails.

thanks :D

**Comment by selul** [comment]
@contactashish13 the goo.gl shortner is not working, i have done some testing here: 

http://ash-test.qsandbox.com/wp-admin/admin.php?page=TweetOldPost 

Can you check if is everything ok ?

**Comment by contactashish13** [comment]
@selul goo.gl is fine now - it expects unencoded URLs but doesn't mention this anywhere in the documentation. Have pushed in the fix.

short.est does not mention this but is okay with encoded URLs.

ow.ly specifies encoded URLs. I have not been able to test this because their support did not respond to my application for access.

**Comment by selul** [comment]
@contactashish13 that's great. thanks
