### ISSUE TITLE
taxonomies filter

### ISSUE THREAD

**Issue by selul** [Codeinwp/tweet-old-post#71]
Hey Ash, 

In the current version we have display all the taxonomies ( categories, tags )  in a checkbox list in order for the users to exclude: http://prntscr.com/bjgelt 

I would like to use this https://harvesthq.github.io/chosen/ , or any other similar library that wordpress comes in. We will group the taxonomies in optgroups, in this way user will be able to search in all of them and we will have an option either to exclude or include the selected taxonomies. 

Please have in mind we need to have backward compatibility here, the previous saved taxonomies exclusion to preserve. IN this way the option to include/exclude will have the exclude value and the taxonomies selected will show in the list.

Let me know if you have any questions.

**Comment by selul** [comment]
@contactashish13 i see that you have added a constant here: https://github.com/Codeinwp/tweet-old-post/commit/4c94f869390817392829f3b85a352fab1469a7e6#diff-3a30915360fe46f26fe3c93ad530953cR23 

You can use the ROPPLUGINPATH, is doing the same thing i think

**Comment by selul** [comment]
@contactashish13 the select all should be removed, it has not point to be there. And we would need a check box either to include or exclude the selected. I think you can add it instead of the select all btn .

**Comment by selul** [comment]
@contactashish13 regardin the include exclude, let's remove the select all btn and one radion button here: 

http://prntscr.com/bp1jhs 

Similar with this one, Radio by buttons example. http://bootstrap.mohrenweiserpartner.de/mopa/bootstrap/forms/choice 

The design is not important, andrei will tackle this. 

Please also take care when selecting the posts to share, either to exclude or include the posts, based on the user choice.

**Comment by contactashish13** [comment]
@selul ROPPLUGINPATH gives the filesystem path, I need the URL hence the constant.

Also, do you want 2 text boxes - one each for include and exclude or only one textbox that works either for exclude or include?

**Comment by selul** [comment]
@contactashish13 yes, you are right regarding the  constant, my bad.

I would like this kind of control above the textarea http://prntscr.com/bpf4of, with two values, include or exclude and one textarea where you select the taxonomies. Based on the radio button choice it will either exclude or include the taxonomies when selecting the posts.
