### ISSUE TITLE
Google Plus

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/tweet-old-post#72]
We can add auto post to Google Plus as suggested by few users in past and one recently. @selul @ineagu

**Comment by ineagu** [comment]
no api for it :(

On Wed, Jun 29, 2016 at 11:27 PM, Hardeep Asrani <notifications@github.com>
wrote:

> We can add auto post to Google Plus as suggested by few users in past and
> one recently. @selul <https://github.com/selul> @ineagu
> <https://github.com/ineagu>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Codeinwp/tweet-old-post/issues/72>, or mute the thread
> <https://github.com/notifications/unsubscribe/ABw6DHAIZejuAkbMLJ2aC8_pw1SIBU8Yks5qQuNGgaJpZM4JBlXg>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by HardeepAsrani** [comment]
Not sure but what about this: https://developers.google.com/+/domains/posts/creating ?

**Comment by ineagu** [comment]
@selul looks like we now have an api : https://developers.google.com/apis-explorer/?hl=en_US#p/plusDomains/v1/plusDomains.activities.insert , the only issue that I see is that like Facebook, it requires a callback domain.

This means that users need to create the app. Maybe @contactashish13 can work on it.

**Comment by selul** [comment]
will be added in the pro version
