### ISSUE TITLE
Test Revive Network Support

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/tweet-old-post#720]
@irinelenache I have attached a version of ROP to this issue. It includes Revive Network support but shouldn't affect the functionality of the base plugin even though Revive Network is not present.

So please do your tests as normal **without Revive Network installed** and ensure everything is working just fine and no new bugs are introduced 

[tweet-old-post.zip](https://github.com/Codeinwp/tweet-old-post/files/5632808/tweet-old-post.zip)

You can see the files changed here: https://github.com/Codeinwp/tweet-old-post/pull/717/files

**Comment by irinelenache** [comment]
@UVLabs found no new issues, seems it's working fine 👍

**Comment by UVLabs** [comment]
@irinelenache Thank you!
