### ISSUE TITLE
Posts still appear in Sharing queue even after being moved to trash

### ISSUE THREAD

**Issue by irinelenache** [Codeinwp/tweet-old-post#726]
If i delete a post it still appears in the Sharing queue until i **Delete it permanently**.
Steps:
1. Create two posts and click **Start sharing**
2. Wait for the first share and then **move to trash** one of the posts https://prnt.sc/vzothp
3. Wait for more shares and look in the **Sharing queue** for the post that is in the trash. https://prnt.sc/vzot48
4. **Delete it permanently** from the trash and look again for the post in the **Sharing queue.**

When i permanently delete the post, it automatically gets out of the sharing queue, i think the same should happen when the post is moved to trash too.

**Comment by UVLabs** [comment]
Fixed this in a past pull request here; https://github.com/Codeinwp/tweet-old-post/commit/5163cb06bc25bc02730d231a32aa844e44a3834a#diff-88a51ea626f8ca32ca9bc09f1893b6acd2af7dc203d18e0bbe3e4b9120dc6cb8R295-R299
