### ISSUE TITLE
Notifications getting triggered too much when there's nothing more to post

### ISSUE THREAD

**Issue by irinelenache** [Codeinwp/tweet-old-post#735]
After all items have been shared and there's nothing more to share, i get these notification every few seconds https://prnt.sc/vzodgm (the notifications should appear only when a new share occurs)
This happens even if RN plugin is activated/deactivated

**Comment by stefan-cotitosu** [comment]
It was addressed in version 9.1.0. [here](https://github.com/Codeinwp/tweet-old-post/pull/987/commits/4abd9b727fcbc4c443d4231325b3215446664ade).
