### ISSUE TITLE
Getting error in log everytime i exclude a post

### ISSUE THREAD

**Issue by irinelenache** [Codeinwp/tweet-old-post#736]
For every post excluded, i get one error in log. The exclusion works fine, but the log looks like this https://prnt.sc/w3vxdg
Is this expected behaviour @UVLabs ?

**Comment by UVLabs** [comment]
This is fixed here: https://github.com/Codeinwp/tweet-old-post/pull/785

**Comment by irinelenache** [comment]
@UVLabs the PR works fine, issue is fixed 👍

**Comment by UVLabs** [comment]
Great, thanks @irinelenache
