### ISSUE TITLE
Remote Cron not working

### ISSUE THREAD

**Issue by purplecodes** [Codeinwp/tweet-old-post#746]
When using the Remote Cron feature, the sharing is not working though you can see that the posts reflected on the sharing queue.

https://snipboard.io/saSo2b.jpg
https://snipboard.io/hcw1iG.jpg

Tested on both the free and pro versions.

**Comment by UVLabs** [comment]
I think there might be something happening on that site that was preventing the cron system from reaching it. Unfortunately, I can't find that site url in the cron system to check it's logs, so it might not be registered with it anymore.

Will leave issue open still
