### ISSUE TITLE
Share immediately feature is not visible on v8.6.6

### ISSUE THREAD

**Issue by purplecodes** [Codeinwp/tweet-old-post#754]
The option to share immediately the post after it has been created is no longer available in v8.6.6
https://snipboard.io/hj36pX.jpg
Tried rolling back to v8.6.4 and the said feature is there.
https://snipboard.io/iSjosr.jpg

Ticket: https://secure.helpscout.net/conversation/1412304693/264364/

**Comment by UVLabs** [comment]
fixed in latest version
