### ISSUE TITLE
Twitter handles not linked

### ISSUE THREAD

**Issue by topher1kenobe** [Codeinwp/tweet-old-post#782]
In Twitter, handles are not linked to their twitter accounts. 

<img width="626" alt="Screen Shot 2021-03-16 at 5 56 50 PM" src="https://user-images.githubusercontent.com/341412/111487422-b885cb00-870e-11eb-87a6-0ed64cfafeb1.png">

**Comment by UVLabs** [comment]
@topher1kenobe I don't think that account exists anymore https://twitter.com/juhi8487 it may have been changed to something else, I tested it out with a different account and it worked

**Comment by UVLabs** [comment]
username was not valid
