### ISSUE TITLE
Encoding issue with tumblr.

### ISSUE THREAD

**Issue by topher1kenobe** [Codeinwp/tweet-old-post#795]
The hyphen in the title on this post: https://heropress.com/essays/a-journey-toward-freedom-with-wordpress/

Is getting encoded as html on tumblr: https://heropress.tumblr.com/post/648544351007522816/a-journey-toward-freedom-with-wordpress-8211

**Comment by UVLabs** [comment]
@topher1kenobe Thanks, this will be patched in the next version, for now you can fix it by changing this line: https://github.com/Codeinwp/tweet-old-post/blob/master/includes/admin/services/class-rop-tumblr-service.php#L452

to:

`$new_post['title']       = html_entity_decode( get_the_title( $post_details['post_id'] ), ENT_QUOTES );
`
