### ISSUE TITLE
Icons does not appear properly when Site Language is set to Japanese and Chinese

### ISSUE THREAD

**Issue by purplecodes** [Codeinwp/tweet-old-post#824]
When you set the Site Language in the WordPress Dashboard to the following:
Japanese
Simplified Chinese
Hong Kong Chinese
Traditional Chinese

https://d.pr/lMzGhQ
Ticket: https://wordpress.org/support/topic/revive-old-posts-icon-is-incorrect-when-site-language-is-set-to-2-byte-language/

**Comment by stefan-cotitosu** [comment]
![icons-on-languages](https://github.com/Codeinwp/tweet-old-post/assets/26867648/69574a74-5e25-4a75-88f0-294b689d10cd)

**Comment by stefan-cotitosu** [comment]
Hey @girishpanchal30, is there any blocker here? I see we didn't start to address the issue yet.

**Comment by girishpanchal30** [comment]
@stefan-cotitosu I missed this because the project team assign is missing here - https://tinyurl.com/2an3f3ht
I'll check and update you here

**Comment by stefan-cotitosu** [comment]
ok, sorry for the confusion; I didn't notice that option

**Comment by girishpanchal30** [comment]
@stefan-cotitosu I've reviewed this issue and fixed it with this PR https://github.com/Codeinwp/tweet-old-post/pull/991
