### ISSUE TITLE
use slug not label name

### ISSUE THREAD

**Issue by selul** [Codeinwp/tweet-old-post#85]
@contactashish13  you are using in the category list setting https://github.com/Codeinwp/tweet-old-post/blob/development/inc/core.php#L2555 the label instead of the slug/name of the taxonomy. In this case if we have multiple taxonomies with same label, which is very likely, they will get overwritten. 

Replicate scenario: 

1 post type with taxonomy categories, having label Categories and slug category
1 post type with taxonomy book_categories, having label Categories and slug book_category. 

In this scenario we will not show both of them because the label is the same, and we use it as key.

Let me know if you have any questions

**Comment by contactashish13** [comment]
@selul are you referring to https://github.com/Codeinwp/tweet-old-post/blob/development/inc/core.php#L2553 or https://github.com/Codeinwp/tweet-old-post/blob/development/inc/core.php#L2555?

**Comment by contactashish13** [comment]
@selul it would be a problem with both. PR: https://github.com/Codeinwp/tweet-old-post/pull/86
