### ISSUE TITLE
Instant sharing not working properly on existing posts

### ISSUE THREAD

**Issue by purplecodes** [Codeinwp/tweet-old-post#861]
### Description

Under the General Settings of Revive Old Posts Dashboard, there is an option **Enable Instant Sharing Feature (Post on Publish)** where the post should automatically be shared to active social media accounts that have been added to the Dashboard after clicking the Publish or Update button.

<img width="1041" alt="Screenshot 2023-03-28 at 4 03 34 AM" src="https://user-images.githubusercontent.com/32997072/228054199-863c2e1f-b998-4a92-b5ae-a1d06a1a24ee.png">

Given the settings (as seen on the screenshot), when a new post has created the socials under the Revive Old Posts setting is automatically selected.

<img width="1352" alt="Screenshot 2023-03-28 at 4 07 51 AM" src="https://user-images.githubusercontent.com/32997072/228054899-6ecd6270-8c87-4bae-9161-1d806258e60e.png">

But the same behavior is not reflected

<img width="1352" alt="Screenshot 2023-03-28 at 4 10 23 AM" src="https://user-images.githubusercontent.com/32997072/228055319-dcd6f395-7364-4180-8190-448df52d473b.png">
 in existing posts.

### Step-by-step reproduction instructions

1. Enable the settings as seen on the screenshot.
2. Create a new post and open an existing post and compare the difference.

### Screenshots, screen recording, code snippet or Help Scout ticket

Ticket: https://secure.helpscout.net/conversation/2182729948/361627?folderId=212385

WP: v6.1.1
ROP(free): v9.0.12
 

### Is the issue you are reporting a regression

Yes, this is a regression.

**Comment by girishpanchal30** [comment]
Hey @purplecodes,

After reviewing the source code, I found the filter that enables the instant sharing option for the edit post screen as well.

Add below code snippet in theme functions.php

```
function top_load_post_callback() {
	add_filter( 'rop_is_edit_post_screen', '__return_false' );
}
add_action( 'load-post.php', 'top_load_post_callback' );
```

Thanks

**Comment by irinelenache** [comment]
@girishpanchal30 I checked and this issue was not happening in the ROP 9.0.2 version and indeed is a regression. Can we fix it in the plugin directly instead of providing custom code?

**Comment by irinelenache** [comment]
@girishpanchal30 Sorry to bother, but can we have the process to build the zip file in the PR as we have in other plugins? I was making the changes myself in the code before, but now there are more changes and it's harder to follow

**Comment by girishpanchal30** [comment]
@irinelenache Can you please download this [file](https://tinyurl.com/2j4bekzc) and replace it with your plugin?

**Comment by irinelenache** [comment]
Checked now and it works fine, thank you 👍
