### ISSUE TITLE
shared post showing as ip instead of wordpress url

### ISSUE THREAD

**Issue by seckingyo** [Codeinwp/tweet-old-post#865]
### Description

i have observed the scheduled posts are using ip of the domain as such 

example

http://1.2.34.3

instead of 

http://domain.com

the wordpress url and site address url is set to http://domain.com

### Step-by-step reproduction instructions

it works fine on first time sharing which happens in 15 seconds or so 
the first scheduled post causes this issue

### Is the issue you are reporting a regression

No

**Comment by vytisbulkevicius** [comment]
Hey @seckingyo,

Can you share a screenshot from Settings->General section of your WordPress dashboard? This area: https://vertis.d.pr/i/Otsq5h with URLs that are set there?

Also, Please follow the steps provided in the screenshot below and share the information by providing it in a link using https://pastebin.com/
<img width="992" alt="image" src="https://user-images.githubusercontent.com/36594177/235601995-9e317a9f-fdc5-422a-9617-4ab38dbb7363.png">

Thanks!

**Comment by vytisbulkevicius** [comment]
Hi @seckingyo,

I'm closing this issue as we haven't received your reply.
If you still face this or any other issue, feel free to post it in our forum here - https://wordpress.org/support/plugin/tweet-old-post/

Thanks!
