### ISSUE TITLE
About page and Upgrade to PRO integration

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/tweet-old-post#868]
### What problem does this address?

As described on this issue we need to add code to ROP that will show about us page and upgrade to PRO via SDK- https://github.com/Codeinwp/themeisle-sdk/pull/178

**Comment by irinelenache** [comment]
@girishpanchal30 Can you please send a zip build for the PR? Thank you

**Comment by girishpanchal30** [comment]
@irinelenache Sure! [tweet-old-post.zip](https://github.com/Codeinwp/tweet-old-post/files/11634768/tweet-old-post.zip)

**Comment by irinelenache** [comment]
@girishpanchal30 Tested and the **About us** works fine 👍 I think we should add the utm tags to the **Upgrade to pro** link https://vertis.d.pr/i/JcwfCA

**Comment by girishpanchal30** [comment]
@irinelenache Added utm tags in the latest commit [tweet-old-post.zip](https://github.com/Codeinwp/tweet-old-post/files/11634995/tweet-old-post.zip)

**Comment by irinelenache** [comment]
@girishpanchal30 Everything's fine now, thank you 🚀
