### ISSUE TITLE
ROP dashboard page doesn't load with LearnPress plugin active

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/tweet-old-post#872]
### Description

There is a conflict causing the Revive Old Post plugin not being usable if LearnPress is active.

### Step-by-step reproduction instructions

1. Install & activate [LearnPress](https://wordpress.org/plugins/learnpress/)
2. Install & activate Revive Old Post
3. Try to open the ROP Dashboard page, it doesn't load

### Screenshots, screen recording, code snippet or Help Scout ticket

![rop-learnpress-issue](https://github.com/Codeinwp/tweet-old-post/assets/26867648/04bdfb3a-d48f-4097-a71c-5e314c7156d1)

Reported here: https://secure.helpscout.net/conversation/2254697720/370899/

### Environment info

https://pastebin.com/jdknKts5

### Is the issue you are reporting a regression

No

**Comment by irinelenache** [comment]
@girishpanchal30 Can you send me a zip build for the PR please?

**Comment by girishpanchal30** [comment]
@irinelenache Sure! https://github.com/Codeinwp/tweet-old-post/files/13250717/tweet-old-post.zip

**Comment by irinelenache** [comment]
@girishpanchal30 The issue is fixed now, thank you 👍
