### ISSUE TITLE
Latest update requires PHP v7.4

### ISSUE THREAD

**Issue by purplecodes** [Codeinwp/tweet-old-post#879]
### Description

ROP requires at least PHP v7.2 or higher and this is also displayed in wp.org. https://vertis.d.pr/i/aBd2JD

But since the last update (v9.0.15), some free users are reporting that they are getting the error below:

_Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.4.0". You are running 7.3.33-10+ubuntu20.04.1+deb.sury.org+1. in /s1-suspendship/wordpress/wp-content/plugins/tweet-old-post/vendor/composer/platform_check.php on line 24
There has been a critical error on this website. Please check your site admin email inbox for instructions._

If this is the new requirement, please update the PHP version requirement on wp.org. 
It would be good as well if there is a way for us to inform the users before they update as they will be locked our from their WordPress Dashboard if they have a lower PHP version than required. 

### Step-by-step reproduction instructions

Steps to replicate:
1. Install and activate the Revive Old Posts plugin. 
2. If your version of PHP is lower than v7.4, you will most likely get the error stated above. 

https://vertis.d.pr/i/m9Zob1

Ticket: https://wordpress.org/support/topic/latest-update-breaks-site-with-php-7-3/

### Is the issue you are reporting a regression

Yes, this is a regression.

**Comment by girishpanchal30** [comment]
@purplecodes Now some composer packages required 7.4 or above PHP version, we need to update the readme.txt file in wp.org
@vytisbulkevicius Can please you please update the readme file?
PR https://github.com/Codeinwp/tweet-old-post/pull/880

**Comment by gingerbeardman** [comment]
It seems like the plugin didn't change so why does requirements? 

Only because of the composer includes?

Is not possible to avoid  using those things that needs 7.4? to retain current compatibilities?

**Comment by girishpanchal30** [comment]
> Only because of some composer packages?

Yes, `abraham/twitteroauth` package required a 7.4 or above PHP version.
![image](https://github.com/Codeinwp/tweet-old-post/assets/79647963/63a244d0-e58f-4846-a972-e9095c6079a2)

Thanks

**Comment by vytisbulkevicius** [comment]
Ignore this, the release is done and the min PHP version appears correctly now.
