### ISSUE TITLE
changes to remote check

### ISSUE THREAD

**Issue by selul** [Codeinwp/tweet-old-post#88]
@contactashish13 i would like to do the following changes to the remote check feature. 
1. remove the current endpoint rop_checking_schedule
2. move the endpoint into rest api, i,e build a rest api call, /rop/v1/trigger_schedule 
3. Please check if the user is using a wordpress version with rest api available, if not dont add the functionality. 
4. The rest api will return an success message, how many networks is using, how many accounts, and if the schedule is started. 

Change the remote check behaviour like this, when the user will enable it, it will send the endpoint address ( previously discussed ) to a 3rd party api. 

The api will return a success message and also a handshake propriety, will have values of yes/no.  If the handshake is yes, means that the 3rd party api can access the ROP endpoint from the user site. If is no, it will mean that 3rd party can  not access the user site. If the handshake is no, we will show on the plugins page, bellow the header a warning message that the user site is not accessible and he needs to allow it. 

Please store the 3rd party response to an rop option and display the warning message based on that option.  This will help the users who are already using the plugin and they have remote check active. 

The call to the 3rd party, will be done each day, but i dont want to use cron for this, use an rop option to store the last call timestamp, and do it by ajax. I.e when the user is on the plugins page, you check with javascript if the time passed and send an ajax request which will do the handshake call. 

You can hardcore the 3rd party api response, for the moment i dont have it ready. 

Regarding the rop options, please dont separate wordpress options for each plugin options, use a master wordpress options for all plugin options.

Let me know if you have questions

**Comment by contactashish13** [comment]
@selul 

1. will the user still activate the remote check or will this be activated by default?
2. if manual, then will the api be called when the toggle is changed?
3. if REST is not enabled, I'm assuming no functionality of remote trigger will be available?

**Comment by selul** [comment]
@contactashish13 

1. Yes, he will still needs to activate. on activate it will send an ajax request ( like is doing now ) call the 3rd party, and display the warning message if handshake is no.

2. yes, when the toggle is changed, and also each day we will check again, if is enabled

3. yes

**Comment by selul** [comment]
@contactashish13 i have thought and for pro users we will not have the toggle, we will always use this.

**Comment by contactashish13** [comment]
@selul PR: https://github.com/Codeinwp/tweet-old-post/pull/90

**Comment by selul** [comment]
@contactashish13 i have added some comments, please check
