### ISSUE TITLE
Plugin conflict with the LearnPress plugin

### ISSUE THREAD

**Issue by kushh23** [Codeinwp/tweet-old-post#887]
### Description

When both the Rop and LearnPress plugins are active on the website, we are experiencing a conflict that prevents the ROP dashboard and exclusion page from opening correctly. 

### Step-by-step reproduction instructions

1. Install and activate Rop plugin.
2. Install and activate LearnPress plugin.
3. Attempt to access the ROP dashboard.

### Screenshots, screen recording, code snippet or Help Scout ticket

HS- https://secure.helpscout.net/conversation/2340831881/383081
https://vertis.d.pr/v/ZEHzs8

### Environment info

https://pastebin.com/01fE4DHz

### Is the issue you are reporting a regression

No

**Comment by girishpanchal30** [comment]
@kushh23 Duplicate of #872, It seems fixed with this PR https://github.com/Codeinwp/tweet-old-post/pull/894
