### ISSUE TITLE
Unable to add Facebook account

### ISSUE THREAD

**Issue by purplecodes** [Codeinwp/tweet-old-post#889]
### Description

Customer is reporting that she is unable to add her Facebook account. Tt just stuck with a blank window after entering the password.
https://vertis.d.pr/i/f0gpS4

### Step-by-step reproduction instructions

1. Installed and activated the Revive Old Posts (free version)
2. Add Facebook account from the Revive Old Posts Dashboard.
3. Enter the password and that is where the blank window got stuck.

### Screenshots, screen recording, code snippet or Help Scout ticket

Test in WP v6.3 and PHP v7.4

Ticket: https://secure.helpscout.net/conversation/2359781492/385381?folderId=212385

### Is the issue you are reporting a regression

No

**Comment by stefan-cotitosu** [comment]
It's also reported [here](https://github.com/Codeinwp/tweet-old-post-pro/issues/454).

We can gather all tickets on the issue started by Poonam since there are many there.

**Comment by vytisbulkevicius** [comment]
We're investigated it here - https://github.com/Codeinwp/tweet-old-post-pro/issues/444

**Comment by poonam279** [comment]
+1 https://secure.helpscout.net/conversation/2363397732/385735/

**Comment by vytisbulkevicius** [comment]
@Codeinwp/qa-team could you please test and confirm this issue is fixed using this PR - https://github.com/Codeinwp/tweet-old-post/pull/890 ? Thanks!

**Comment by irinelenache** [comment]
@vytisbulkevicius I tested with the wordpress.org version and connecting & sharing worked fine for facebook 👍 
@girishpanchal30 Can you add the zip build for the mentioned PR so i can test the changes there?

**Comment by girishpanchal30** [comment]
@irinelenache https://github.com/Codeinwp/tweet-old-post/files/12657867/tweet-old-post.zip

**Comment by irinelenache** [comment]
@vytisbulkevicius Tested using the PR build now and connecting & sharing to facebook work as expected on my end 🚀

**Comment by vytisbulkevicius** [comment]
@Codeinwp/support this issue is now fixed, please inform the affected users. Thanks!

**Comment by stefan-cotitosu** [comment]
Thank you, @vytisbulkevicius. Done; I've informed all the affected users who reported it.
