### ISSUE TITLE
A function to download error log that can be easily shared with us

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/tweet-old-post#902]
### What problem does this address?

In the Sharing logs section where errors are printed:
<img width="1121" alt="image" src="https://github.com/Codeinwp/tweet-old-post/assets/36594177/527721fc-2405-4f04-9501-fdcb306988ea">
We can add a button that downloads the error log file so clients don't need to make the screenshot where not all errors are always visible.

### Will this feature require documentation? (Optional)

None

**Comment by mghenciu** [comment]
**Will the Download option have any options?** for example a dropdown, like download logs from Today | Last 7 days | Last 30 Days | All Logs.

or just be a Download all logs, and that's it?

**Comment by vytisbulkevicius** [comment]
I think it's fine to download all logs @mghenciu, as it's plain text file it should still be small.
