### ISSUE TITLE
Social media accounts are not selected with Instant sharing activated

### ISSUE THREAD

**Issue by irinelenache** [Codeinwp/tweet-old-post#907]
### Description

Since the last update, when the **Instant sharing by default** option is activated, the share is enabled in the editor but the social medias are not checked https://vertis.d.pr/i/vrfmQQ

With ROP 9.0.22 it works fine

Ticket - https://secure.helpscout.net/conversation/2498148891/402766?folderId=212385

### Step-by-step reproduction instructions

1. Enable the **Instant sharing by default** option
2. Create a new post and check if the social medias are selected

### Screenshots, screen recording, code snippet or Help Scout ticket

https://vertis.d.pr/i/vrfmQQ

### Environment info

WordPress 6.4.3 / ROP 9.0.23

### Is the issue you are reporting a regression

Yes, this is a regression.

**Comment by poonam279** [comment]
+1 https://secure.helpscout.net/conversation/2502306569/403332/

**Comment by AndreeaCristinaRadacina** [comment]
+1 https://secure.helpscout.net/conversation/2505103103/403839?viewId=931544

**Comment by AndreeaCristinaRadacina** [comment]
+1 https://wordpress.org/support/topic/sharing-to-box-isnt-ticked-by-default-anymore/
