### ISSUE TITLE
Share posts as image not longer available in X

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/tweet-old-post#920]
### Description

A customer asked about the sharing posts as an image feature, which seems to be no longer available in ROP.

ref: https://secure.helpscout.net/conversation/2513858320/405065?viewId=212385

### Step-by-step reproduction instructions

1. Go to ROP > Posts Format
2. Scroll down to the Share As Image Post feature

### Screenshots, screen recording, code snippet or Help Scout ticket

<img width="1037" alt="image" src="https://github.com/Codeinwp/tweet-old-post/assets/86592992/f481d141-4ede-494d-8f78-e5ca748d2aca">

### Is the issue you are reporting a regression

Yes, this is a regression.

**Comment by Soare-Robert-Daniel** [comment]
@AndreeaCristinaRadacina, the image sharing is only available to users who use `Use my own API keys` option.

**Comment by AndreeaCristinaRadacina** [comment]
@Soare-Robert-Daniel thank you for sharing! I will create a doc update request in this case. Thank you!

**Comment by AndreeaCristinaRadacina** [comment]
@vytisbulkevicius do you think it is worth it to clarify this in the feature's description inside the plugin too? Maybe adding the link to that doc?
