### ISSUE TITLE
Enable dependabot to fetch SDK updates automatically

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/tweet-old-post#924]
### What problem does this address?

As we discussed on Slack this repository doesn't get SDK updates automatically so it would be good to have it added.

### Will this feature require documentation? (Optional)

None

**Comment by preda-bogdan** [comment]
This should be now present on `master`.
A note here for the first few merges except the `themeisle-sdk` we should ensure nothing breaks when updating the packages as I see some of them might add breaking changes and we might need to pin the versions.
