### ISSUE TITLE
Pinterest icon available in Dashboard

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/tweet-old-post#925]
This is more like a question:

A user asked for a refund after he saw Pinterest is not actually available in ROP.
I checked the dashboard, but I couldn't find anything about it.

Are you aware of something like this?

ref: https://secure.helpscout.net/conversation/2526547443/406572?viewId=212385

**Comment by vytisbulkevicius** [comment]
I don't see Pinterest icon anywhere in the dashboard or page as well
