### ISSUE TITLE
Hashtags from categories don't work as expected

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/tweet-old-post#942]
### Description

A user reported that when using Create Hashtags from Categories if the title/content contains the name of the category, those words will be marked as hashtags.

ref: https://wordpress.org/support/topic/disable-hashtags-in-content/

### Step-by-step reproduction instructions

1. Connect ROP
2. In Post Format set the Share Content to Post Title (try with Post Content too)
3. In Hashtags set to create hashtags from categories
4. Create a post and assign it to a certain category 
5. Take the name of the category and put it in the title
6. Save and check the sharing queue

### Screenshots, screen recording, code snippet or Help Scout ticket

<img width="976" alt="image" src="https://github.com/Codeinwp/tweet-old-post/assets/86592992/4f9c0cb7-e2d6-4cd6-8ead-01978b0305c7">
<img width="1076" alt="image" src="https://github.com/Codeinwp/tweet-old-post/assets/86592992/9c1566a3-5725-4c0e-a7b5-90ff840237a3">

Post content:
<img width="1349" alt="image" src="https://github.com/Codeinwp/tweet-old-post/assets/86592992/3c1e7490-f342-44c4-81b5-201a811721cc">
<img width="896" alt="image" src="https://github.com/Codeinwp/tweet-old-post/assets/86592992/7a2f240e-f138-4694-bf06-fbf2ede7a7ee">

Post title:
<img width="825" alt="image" src="https://github.com/Codeinwp/tweet-old-post/assets/86592992/71391694-4b40-41ad-8317-c3c29b8125c0">

### Is the issue you are reporting a regression

No

**Comment by vytisbulkevicius** [comment]
@AndreeaCristinaRadacina,

To me it sounds the same as here - https://github.com/Codeinwp/tweet-old-post-pro/issues/483 and we confirmed it's desired behavior. You can add +1 there and close this issue if you confirm it's the same, we checked it then and did not find that one way of doing it is better than the other (using existing word from the content as hashtag VS adding a separate word with a hashtag after the content)
