### ISSUE TITLE
Facebook sunset 3-rd party apps for Groups

### ISSUE THREAD

**Issue by Soare-Robert-Daniel** [Codeinwp/tweet-old-post#949]
### Description

Facebook has removed 3-rd party access to groups.

![image](https://github.com/Codeinwp/tweet-old-post/assets/17597852/e5df9a75-e4ae-45fa-ab35-b034f83cde18)

![image](https://github.com/Codeinwp/tweet-old-post/assets/17597852/1d4f6f0d-80ea-43d5-8b0f-ffba3f76a48f)

Also our Sign In Facebook is no longer valid

![image](https://github.com/Codeinwp/tweet-old-post/assets/17597852/0626e4ea-2d32-46bc-8bf0-92633035aa3c)

I think we also need to remove the `publish_on_groups` permission from the sign in request

### Step-by-step reproduction instructions

1. Install RoP
2. Try to sign in with Facebook

### Screenshots, screen recording, code snippet or Help Scout ticket

- https://secure.helpscout.net/conversation/2578654792/416600/
- https://secure.helpscout.net/conversation/2577658106/416491/

### Is the issue you are reporting a regression

No

**Comment by AndreeaCristinaRadacina** [comment]
+2 https://wordpress.org/support/topic/unable-to-share-new-posts-on-facebook-groups/
