### ISSUE TITLE
Start here button from the header has a confusing behaviour.

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/tweet-old-post#951]
### Description

There is a start here button that I thought would start sharing, but when clicked it would send me to a YouTube playlist, completely unexpected UX.

I would suggest we move that to the sidebar and rename it what it is: Video tutorials.

### Step-by-step reproduction instructions

https://vertis.d.pr/i/9GD8gY

### Is the issue you are reporting a regression

No

**Comment by stefan-cotitosu** [comment]
I couldn't find more recent videos, so I suggest removing the button without adding it to the sidebar. There is the docs button in the sidebar.
