### ISSUE TITLE
Instant sharing setting is hard to find.

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/tweet-old-post#952]
### What problem does this address?

Right now we have instant sharing on publish, but it is displayed as a metabox in the sidebar which I couldn't find and customers aren't noticing it.

### What is your proposed solution?

Move the panel here : https://vertis.d.pr/i/2Hi46t, after the user is clicking publish on a post.

### Will this feature require documentation? (Optional)

None

**Comment by girishpanchal30** [comment]
@stefan-cotitosu I've reviewed the issue and found we can't move the meta box to the `PrePublish` sidebar.
Here I found an `Gutenberg` open ticket related to this issue - https://github.com/WordPress/gutenberg/issues/17112

Please let me know if you have any suggestions for this issue.

Thanks
