### ISSUE TITLE
Remove Facebook Groups from ROP dashboard

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/tweet-old-post#953]
A user reported that even if he removed the Facebook groups from the Accounts page, those are still displayed in the Post Format panel:
<img width="970" alt="Screenshot 2024-04-29 at 10 39 03 PM" src="https://github.com/Codeinwp/tweet-old-post/assets/86592992/97e14fc6-c296-4dc4-bf55-f61dd79cee96">
<img width="962" alt="Screenshot 2024-04-29 at 10 39 17 PM" src="https://github.com/Codeinwp/tweet-old-post/assets/86592992/c7985af5-b8e4-471a-9986-454fa0be6cc4">

I cannot replicate this because there was no Facebook account linked to my Facebook profile before this latest change.

**Comment by AndreeaCristinaRadacina** [comment]
Update: the groups appear in more tabs.

**Comment by gimmiefreebies** [comment]
Thanks, this problem persists. Any update?

**Comment by gimmiefreebies** [comment]
There was an update to ROP lite which did not fix my problem, FYI.

**Comment by AndreeaCristinaRadacina** [comment]
@Soare-Robert-Daniel, thank you for taking care!

Unfortunately, I don't have an old Group Facebook page to test the functionality. No fatal error was triggered, but I cannot test the functionality.

@Codeinwp/support, is there anyone who previously had a group Facebook page who can test this?

**Comment by stefan-cotitosu** [comment]
@AndreeaCristinaRadacina, I don't have the Facebook group connected anymore, but after we release the fix, you can inform the users who reported this issue. They should be able to confirm if it works.

**Comment by stefan-cotitosu** [comment]
It should be resolved as it was addressed in version 9.1.0.
