### ISSUE TITLE
Plugin description contains broken Contact link

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/tweet-old-post#966]
### Description

![Annotation on 2024-06-20 at 14-20-39](https://github.com/Codeinwp/tweet-old-post/assets/3266155/2bfd5691-6d49-4b7f-99f1-8bf0ca333445)

![Screenshot on 2024-06-20 at 14-22-28](https://github.com/Codeinwp/tweet-old-post/assets/3266155/7d88e42b-73bc-4bac-a1f3-fbd888bf1dba)

### Step-by-step reproduction instructions

Both ROP Free and ROP Pro have a Contact us link in their description but that link is broken.
Plus, I think it should open in a new tab.

### Is the issue you are reporting a regression

No

**Comment by selul** [comment]
this was fixed in the last release.
