### ISSUE TITLE
Account menu item from https://revive.social/ links to 404page

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/tweet-old-post#967]
### Description

![Annotation on 2024-06-20 at 18-06-06](https://github.com/Codeinwp/tweet-old-post/assets/3266155/57a938ac-7ef9-4c1e-8e92-d40aca3f2034)

### Step-by-step reproduction instructions

Go to https://revive.social/ and click on Account

### Is the issue you are reporting a regression

No

**Comment by selul** [comment]
working now, seems like someone archived the page that it used to be there.
