### ISSUE TITLE
Update the Upgrade button in the right sidebar in the Dashboard

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/tweet-old-post#971]
### What problem does this address?

It leads to the product page without scrolling to the pricing plans.

### What is your proposed solution?

Add a link to the pricing section in this button once [this](https://github.com/Codeinwp/tweet-old-post-pro/issues/522) is complete.

### Will this feature require documentation? (Optional)

No.

**Comment by girishpanchal30** [comment]
Hey @stefan-cotitosu,

> once this is complete.

I see this https://github.com/Codeinwp/tweet-old-post-pro/issues/522 ticket is closed now, Should I add the below link to the sidebar upgrade button(https://tinyurl.com/2pg2l26s)?

Upgrade link: https://revive.social/plugins/revive-old-post/?utm_source=wpadmin&utm_medium=sidebar&utm_campaign=pro#pricing

Thanks

**Comment by stefan-cotitosu** [comment]
Hey @girishpanchal30, there is no need to change this link anymore. You understood my request well, but we have changed the plan here.
