### ISSUE TITLE
ROP stopped posting on Facebook again

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/tweet-old-post#973]
### Description

Users came back with a past issue. The posts are no longer shared on Facebook, and this error appears:
Preparing authorization… No Facebook pages or groups were given authorization for posting. Please make sure you have higher access to a Facebook page or group.

It didn't happen on my website too, I am not sure what is different on their side. Indeed, after I removed the admin rights on my side, the page was removed from ROP Dashboard.

### Step-by-step reproduction instructions

1. Connect ROP to a Facebook page
2. Start the sharing

### Screenshots, screen recording, code snippet or Help Scout ticket

https://wordpress.org/support/topic/too-many-requests-error-message/#post-17823676

### Is the issue you are reporting a regression

Yes, this is a regression.

**Comment by AndreeaCristinaRadacina** [comment]
+1 https://secure.helpscout.net/conversation/2641379932/424232?viewId=212385

**Comment by AndreeaCristinaRadacina** [comment]
+1 https://secure.helpscout.net/conversation/2641366340/424229/

**Comment by AndreeaCristinaRadacina** [comment]
+1 https://secure.helpscout.net/conversation/2641216101/424190/

**Comment by Soare-Robert-Daniel** [comment]
@AndreeaCristinaRadacina I updated the Facebook permission on the server. You can tell the users to try again 🙏

**Comment by AndreeaCristinaRadacina** [comment]
Thank you, @Soare-Robert-Daniel!
