### ISSUE TITLE
Change links on WP.org page

### ISSUE THREAD

**Issue by s2abina** [Codeinwp/tweet-old-post#99]
On this page https://wordpress.org/plugins/tweet-old-post/

*\* Useful Resources **
Check-out our _tutorials site_  - ok
Take a look at our other _plugins_. - change link to  https://revive.social/
Read more about WordPress on _our blog_.  > change link to https://revive.social/blog/

cc @mariusghitulescu

**Comment by mariusghitulescu** [comment]
Le-as lasa asa pana avem ce continut sa le oferim.
Other plugins nu exista inca, RN nu e gata.
Blogul inca nu prea are continut.
